-- Auto-generated from schema-map-postgres.yaml (map@sha1:6D9B52237D942B2B3855FD0F5500331B935A7C62)
-- engine: postgres
-- table:  slo_status

CREATE TABLE IF NOT EXISTS slo_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_id BIGINT NOT NULL,
  computed_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  sli_value NUMERIC(18,6) NULL,
  good_events BIGINT NOT NULL DEFAULT 0,
  total_events BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'unknown',       -- 'good','breach','unknown'
  CONSTRAINT uq_slo_status_window UNIQUE (window_id, computed_at),
  CONSTRAINT chk_slo_status CHECK (status IN ('good','breach','unknown'))
);
